#!/usr/bin/env bash

export RUST_LOG=kerblam=trace
export RUST_BACKTRACE=1
cargo build --manifest-path /home/hedmad/Files/repos/kerblam/Cargo.toml
/home/hedmad/Files/repos/kerblam/target/debug/kerblam "$@"
