name: test suite
on: [pull_request]

env:
  RUST_LOG: debug
  RUST_BACKTRACE: 1

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y tree
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features -- --nocapture
